### ISSUE TITLE
Glow on any UIView

### ISSUE THREAD

**Issue by pjebs** [scihant/CTShowcase#4]
How can I make the dynamic glow happen on any UIView that I have?

Do I need to subclass my UIView to get access to `draw`?

**Comment by scihant** [comment]
It can already happen on any view. Dynamic highlights are drawn using sublayers added to a view that covers to entire screen. The effects aren't drawn on the highlighted view itself. Therefore you can use the `CTDynamicGlowHighlighter` class to draw the highlight on any view you have. If you want to change the effect with a custom one, then you need to create a new class conforming to the `CTRegionHighlighter` protocol.

**Comment by pjebs** [comment]
How do I use your class to just add a glow to any UIView without all the other showcase stuff?

**Comment by scihant** [comment]
You can't. Highlighter classes aren't meant to be used as standalone. If you want to use them to draw effects to a view, you need to do the exact same thing `CTShowcaseView`does, which is, creating a view that covers the screen, adding the layer of the highlighter to it as a sublayer at the correct coordinates, and overriding its `draw(_:)` method to clear the region that corresponds to the location of your target view.

If you want to draw on the context of an `UIView`'s layer directly, then you need to copy all the drawing code and modify them so that they can be used on the view directly.

I'm closing the issue because it isn't really an issue with the library.
